version: '3.8'

services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    restart: always # This ensures the server restarts if it crashes or the host reboots
    environment:
      - PORT=5000